drop table if exists ACCOUNTS;
drop table if exists CARDS;
drop table if exists CLIENTS;

CREATE TABLE CLIENTS
(
    CLIENT_ID INT NOT NULL
);

CREATE TABLE ACCOUNTS (
    ACCOUNT VARCHAR(40) NOT NULL,
    BALANCE DOUBLE DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'RUR',
    CLIENT_ID INT NOT NULL,
    PRIMARY KEY (ACCOUNT),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID));

CREATE TABLE CARDS
(
    ACCOUNT VARCHAR(40) NOT NULL,
    CARD    VARCHAR(16) NOT NULL,
    PIN     INT         NOT NULL,
    FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNTS (ACCOUNT)
);
